version: '3.1'
services:

  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gis-together
    volumes:
      - ./database/account_user_table.sql:/docker-entrypoint-initdb.d/account_user_table.sql

  activemq:
    image: symptoma/activemq:latest
    container_name: activemq
    ports: 
      - 61616:61616
      - 61613:61613
      - 8161:8161
      - 5672:5672
      - 1883:1883
    environment:
      - ACTIVEMQ_CONFIG_QUEUES_insertedGeojson=insertedGeojson

  gis-geo-importer:
    image: gis-geo-importer
    build:
      context: ./gis-geo-importer/
      dockerfile: Dockerfile
    container_name: gis-geo-importer
    hostname: gis-geo-importer
    depends_on:
      - activemq
      - gis-account-service
    ports:
      - 8081:8080
    restart: always

  gis-geodata-service:
    image: gis-geodata-service
    build:
      context: ./gis-geodata-service/
      dockerfile: Dockerfile
    container_name: gis-geodata-service
    hostname: gis-geodata-service
    depends_on:
      - activemq
      - gis-account-service
    ports:
      - 8082:8080
    restart: always

  gis-account-service:
    image: gis-account-service
    build:
      context: ./gis-account-service/
      dockerfile: Dockerfile.jvm
    container_name: gis-account-service
    hostname: gis-account-service
    depends_on:
      - postgres
    ports:
      - 8083:8080
      - 8443:8443
      - 9000:9000
    restart: always