version: '3.1'
services:

  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gis-together
    volumes:
      - ./database/account_user_table.sql:/docker-entrypoint-initdb.d/account_user_table.sql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  gis-geo-importer:
    image: gis-geo-importer
    build:
      context: ./gis-geo-importer/
      dockerfile: Dockerfile
    container_name: gis-geo-importer
    hostname: gis-geo-importer
    depends_on:
      - rabbitmq
      - gis-account-service
    ports:
      - 8081:8081
    restart: always

  gis-geodata-service:
    image: gis-geodata-service
    build:
      context: ./gis-geodata-service/
      dockerfile: Dockerfile
    container_name: gis-geodata-service
    hostname: gis-geodata-service
    depends_on:
      - rabbitmq
      - gis-account-service
    ports:
      - 8082:8082
    restart: always

  gis-account-service:
    image: gis-account-service
    build:
      context: ./gis-account-service/
      dockerfile: Dockerfile
    container_name: gis-account-service
    hostname: gis-account-service
    depends_on:
      - postgres
    ports:
      - 8083:8083
      - 8443:8443
      - 9000:9000
    restart: always