version: '3.1'
services:

  activemq:
    image: symptoma/activemq:latest
    container_name: activemq
    ports: 
      - 61616:61616
      - 61613:61613
      - 8161:8161
      - 5672:5672
      - 1883:1883
    environment:
      - ACTIVEMQ_CONFIG_QUEUES_insertedGeojson=insertedGeojson

  gis-geo-importer:
    image: gis-geo-importer
    build:
      context: ./gis-geo-importer/
      dockerfile: Dockerfile
    container_name: gis-geo-importer
    hostname: gis-geo-importer
    depends_on:
      - activemq
    ports:
      - "8081:8080"
    restart: always

  gis-geodata-service:
    image: gis-geodata-service
    build:
      context: ./gis-geodata-service/
      dockerfile: Dockerfile
    container_name: gis-geodata-service
    hostname: gis-geodata-service
    depends_on:
      - activemq
    ports:
      - "8082:8080"
    restart: always