// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JwtGrpc.proto

package si.um.feri.gisgeodataservice.proto;

public final class JwtGrpcProto {
  private JwtGrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_JwtRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_JwtRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_JwtValidReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_JwtValidReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rJwtGrpc.proto\022\005proto\"\033\n\nJwtRequest\022\r\n\005" +
      "token\030\001 \001(\t\"\036\n\rJwtValidReply\022\r\n\005valid\030\001 " +
      "\001(\t2H\n\007JwtGrpc\022=\n\020CheckJwtValidity\022\021.pro" +
      "to.JwtRequest\032\024.proto.JwtValidReply\"\000B4\n" +
      "\"si.um.feri.gisgeodataservice.protoB\014Jwt" +
      "GrpcProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_JwtRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_JwtRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_JwtRequest_descriptor,
        new String[] { "Token", });
    internal_static_proto_JwtValidReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_JwtValidReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_JwtValidReply_descriptor,
        new String[] { "Valid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
