// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JwtGrpc.proto

package si.um.feri.gisgeodataservice.proto;

public interface JwtRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.JwtRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
