// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JwtGrpc.proto

package si.um.feri.gisgeodataservice.proto;

public interface JwtValidReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.JwtValidReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string valid = 1;</code>
   * @return The valid.
   */
  String getValid();
  /**
   * <code>string valid = 1;</code>
   * @return The bytes for valid.
   */
  com.google.protobuf.ByteString
      getValidBytes();
}
