// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.2
// source: JwtGrpc.proto

package GisGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JwtRequest) Reset() {
	*x = JwtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_JwtGrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtRequest) ProtoMessage() {}

func (x *JwtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_JwtGrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtRequest.ProtoReflect.Descriptor instead.
func (*JwtRequest) Descriptor() ([]byte, []int) {
	return file_JwtGrpc_proto_rawDescGZIP(), []int{0}
}

func (x *JwtRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JwtValidReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid string `protobuf:"bytes,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *JwtValidReply) Reset() {
	*x = JwtValidReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_JwtGrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtValidReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtValidReply) ProtoMessage() {}

func (x *JwtValidReply) ProtoReflect() protoreflect.Message {
	mi := &file_JwtGrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtValidReply.ProtoReflect.Descriptor instead.
func (*JwtValidReply) Descriptor() ([]byte, []int) {
	return file_JwtGrpc_proto_rawDescGZIP(), []int{1}
}

func (x *JwtValidReply) GetValid() string {
	if x != nil {
		return x.Valid
	}
	return ""
}

var File_JwtGrpc_proto protoreflect.FileDescriptor

var file_JwtGrpc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x4a, 0x77, 0x74, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0a, 0x4a, 0x77, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x25, 0x0a, 0x0d, 0x4a, 0x77,
	0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x32, 0x48, 0x0a, 0x07, 0x4a, 0x77, 0x74, 0x47, 0x72, 0x70, 0x63, 0x12, 0x3d, 0x0a, 0x10,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4a, 0x77, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x77, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x77, 0x74, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f,
	0x47, 0x69, 0x73, 0x47, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_JwtGrpc_proto_rawDescOnce sync.Once
	file_JwtGrpc_proto_rawDescData = file_JwtGrpc_proto_rawDesc
)

func file_JwtGrpc_proto_rawDescGZIP() []byte {
	file_JwtGrpc_proto_rawDescOnce.Do(func() {
		file_JwtGrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_JwtGrpc_proto_rawDescData)
	})
	return file_JwtGrpc_proto_rawDescData
}

var file_JwtGrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_JwtGrpc_proto_goTypes = []interface{}{
	(*JwtRequest)(nil),    // 0: proto.JwtRequest
	(*JwtValidReply)(nil), // 1: proto.JwtValidReply
}
var file_JwtGrpc_proto_depIdxs = []int32{
	0, // 0: proto.JwtGrpc.CheckJwtValidity:input_type -> proto.JwtRequest
	1, // 1: proto.JwtGrpc.CheckJwtValidity:output_type -> proto.JwtValidReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_JwtGrpc_proto_init() }
func file_JwtGrpc_proto_init() {
	if File_JwtGrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_JwtGrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_JwtGrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtValidReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_JwtGrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_JwtGrpc_proto_goTypes,
		DependencyIndexes: file_JwtGrpc_proto_depIdxs,
		MessageInfos:      file_JwtGrpc_proto_msgTypes,
	}.Build()
	File_JwtGrpc_proto = out.File
	file_JwtGrpc_proto_rawDesc = nil
	file_JwtGrpc_proto_goTypes = nil
	file_JwtGrpc_proto_depIdxs = nil
}
