name: Run auto tests

on: [push]

jobs:
  test-gis-geo-importer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install dependencies
        run: |
          cd ./gis-geo-importer
          go get .
      - name: Build gis-geo-importer
        run: |
          cd ./gis-geo-importer
          go build
      - name: Test gis-geo-importer
        run: |
          cd ./gis-geo-importer
          go test -v gis-geo-importer/test -json > TestResults.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResultsGoLang
          path: ./gis-geo-importer/TestResults.json
      - name: Download Go test results
        uses: actions/download-artifact@v3
        with:
          name: TestResultsGoLang

  test-gis-geodata-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build
        run: |
          cd ./gis-geodata-service
          mvn --batch-mode -DskipTests package
      - name: Test
        run: |
          cd ./gis-geodata-service
          mvn --batch-mode -Dmaven.test.failure.ignore=false test    
      - name: Upload Spring Boot test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResultsSpringBoot
          path: ./gis-geodata-service/target/surefire-reports/*.txt
      - name: Download Spring Boot test results
        uses: actions/download-artifact@v3
        with:
          name: TestResultsSpringBoot


  test-gis-account-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build
        run: |
          cd ./gis-account-service
          mvn --batch-mode -DskipTests package
      - name: Test
        run: |
          cd ./gis-account-service
          mvn --batch-mode -Dmaven.test.failure.ignore=false test    
      - name: Upload Quarkus test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResultsQuarkus
          path: ./gis-account-service/target/surefire-reports/*.txt
      - name: Download Quarkus test results
        uses: actions/download-artifact@v3
        with:
          name: TestResultsQuarkus